/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ada.protende;

/**
 *
 * @author ada
 */
public class LoadJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoadJFrame
     */
    public LoadJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carregmamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 460, 30);

        jLabel2.setText("Peso próprio");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 100, 20);

        jLabel3.setText("Demais ações permanentes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 110, 210, 20);

        jLabel4.setText("Ação variável principal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 170, 20);

        jLabel5.setText("Ação variável secundária");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 170, 190, 20);

        jLabel6.setText("kNm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(390, 80, 32, 19);

        jLabel7.setText("kNm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 110, 32, 19);

        jLabel8.setText("kNm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 140, 32, 19);

        jLabel9.setText("kNm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 170, 32, 19);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(260, 80, 90, 25);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(260, 110, 90, 25);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(260, 140, 90, 25);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(260, 170, 90, 25);

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Momentos fletores"));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 250, 480, 150);

        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Momentos fletores"));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 50, 480, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
