/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ada.protende;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.Converter;

/**
 *
 * @author ada
 */
public class LoadJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoadJFrame
     */
    public LoadJFrame() {
        initComponents();
    }

    private double selfLoadMoment;
    private double othersDeadLoadMoment;
    private double principalLiveLoadMoment;
    private double othersLiveLoadMoment;
    private double psi_1;
    private double psi_2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        selfLoadTextFiled = new javax.swing.JTextField();
        othersDeadLoadTextField = new javax.swing.JTextField();
        liveLoadPrincipalMomentTextField = new javax.swing.JTextField();
        liveLoadSecundaryMomentTextField = new javax.swing.JTextField();
        pis_2_coeff_textField = new javax.swing.JTextField();
        psi_1_CoeffTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        confirmLoadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 450));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carregmamento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 30);

        jLabel2.setText("Peso próprio");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 80, 100, 20);

        jLabel3.setText("Demais ações permanentes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 210, 20);

        jLabel4.setText("Ação variável principal");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 160, 170, 20);

        jLabel5.setText("Ação variável secundária");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 200, 190, 20);

        jLabel6.setText("kNcm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(330, 80, 40, 16);

        jLabel7.setText("kNcm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(330, 120, 40, 20);

        jLabel8.setText("kNcm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 160, 40, 16);

        jLabel9.setText("kNcm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 200, 40, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Coeficientes de ponderação no Estado Limite de Serviço");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 260, 400, 16);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Momentos fletores");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 30, 400, 16);

        jLabel12.setText("<html> &#968<sub>2<sub>");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 330, 20, 16);

        jLabel13.setText("<html> &#968<sub>1<sub>");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 300, 20, 22);
        getContentPane().add(selfLoadTextFiled);
        selfLoadTextFiled.setBounds(200, 80, 90, 22);
        getContentPane().add(othersDeadLoadTextField);
        othersDeadLoadTextField.setBounds(200, 120, 90, 22);
        getContentPane().add(liveLoadPrincipalMomentTextField);
        liveLoadPrincipalMomentTextField.setBounds(200, 160, 90, 22);
        getContentPane().add(liveLoadSecundaryMomentTextField);
        liveLoadSecundaryMomentTextField.setBounds(200, 200, 90, 22);
        getContentPane().add(pis_2_coeff_textField);
        pis_2_coeff_textField.setBounds(50, 330, 64, 22);
        getContentPane().add(psi_1_CoeffTextField);
        psi_1_CoeffTextField.setBounds(50, 300, 64, 22);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 280, 380, 90);

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 50, 380, 190);

        confirmLoadButton.setText("Confirmar");
        confirmLoadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmLoadButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmLoadButton);
        confirmLoadButton.setBounds(270, 330, 100, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmLoadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmLoadButtonActionPerformed

        trhowExceptionIfJTexTFieldIsEmpty(selfLoadTextFiled);
        this.selfLoadMoment = Converter.textToDouble(selfLoadTextFiled);

        trhowExceptionIfJTexTFieldIsEmpty(othersDeadLoadTextField);
        this.othersDeadLoadMoment = Converter.textToDouble(othersDeadLoadTextField);

        trhowExceptionIfJTexTFieldIsEmpty(liveLoadPrincipalMomentTextField);
        this.principalLiveLoadMoment = Converter.textToDouble(liveLoadPrincipalMomentTextField);

        trhowExceptionIfJTexTFieldIsEmpty(liveLoadSecundaryMomentTextField);
        this.othersLiveLoadMoment = Converter.textToDouble(liveLoadSecundaryMomentTextField);

        trhowExceptionIfJTexTFieldIsEmpty(psi_1_CoeffTextField);
        this.psi_1 = Converter.textToDouble(psi_1_CoeffTextField);

        trhowExceptionIfJTexTFieldIsEmpty(pis_2_coeff_textField);
        this.psi_2 = Converter.textToDouble(pis_2_coeff_textField);

        System.out.println("Salvando dados de carregamento...");
        this.dispose();
    }//GEN-LAST:event_confirmLoadButtonActionPerformed

    public double getSelfLoadMoment() {
        return selfLoadMoment;
    }

    public double getOthersDeadLoadMoment() {
        return othersDeadLoadMoment;
    }

    public double getPrincipalLiveLoadMoment() {
        return principalLiveLoadMoment;
    }

    public double getOthersLiveLoadMoment() {
        return othersLiveLoadMoment;
    }

    public double getPsi_1() {
        return psi_1;
    }

    public double getPsi_2() {
        return psi_2;
    }

    private void trhowExceptionIfJTexTFieldIsEmpty(JTextField textField) {
        if (textField.getText().trim().isEmpty()) { // trim() remove espaços em branco
            JOptionPane.showMessageDialog(null, "Campos de texto de texto não pode estar vazio.");
            throw new IllegalArgumentException("TextField cannot be empty");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmLoadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField liveLoadPrincipalMomentTextField;
    private javax.swing.JTextField liveLoadSecundaryMomentTextField;
    private javax.swing.JTextField othersDeadLoadTextField;
    private javax.swing.JTextField pis_2_coeff_textField;
    private javax.swing.JTextField psi_1_CoeffTextField;
    private javax.swing.JTextField selfLoadTextFiled;
    // End of variables declaration//GEN-END:variables
}
