/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ada.protende;

import com.ada.prestressedCalc.PrestressedCalc;
import javax.swing.JOptionPane;

/**
 *
 * @author olgierd
 */
public class MaterialJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MaterialJFrame
     */
    public MaterialJFrame() {
        initComponents();
    }
    private double fck = 0.0;
    private double tendonDiameter = 0.0;
    private double tendonTension = 0.0;
    private double passiveSteelBar = 0.0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fckButtonGroup = new javax.swing.ButtonGroup();
        prestressedSteelButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        C40 = new javax.swing.JRadioButton();
        C45 = new javax.swing.JRadioButton();
        C50 = new javax.swing.JRadioButton();
        C55 = new javax.swing.JRadioButton();
        C60 = new javax.swing.JRadioButton();
        C65 = new javax.swing.JRadioButton();
        C70 = new javax.swing.JRadioButton();
        C75 = new javax.swing.JRadioButton();
        C80 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CP190_127 = new javax.swing.JRadioButton();
        CP190_152 = new javax.swing.JRadioButton();
        CP190_157 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 500));
        setPreferredSize(new java.awt.Dimension(350, 455));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Propriedades dos materiais");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 20);

        jLabel2.setText("Armadura passiva");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(6, 202, 94, 16);

        jLabel3.setText("Armadura Ativa (cordoalhas engraxadas)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 269, 214, 16);

        fckButtonGroup.add(C40);
        C40.setText("C40");
        getContentPane().add(C40);
        C40.setBounds(20, 46, 45, 21);

        fckButtonGroup.add(C45);
        C45.setText("C45");
        getContentPane().add(C45);
        C45.setBounds(20, 76, 45, 21);

        fckButtonGroup.add(C50);
        C50.setText("C50");
        getContentPane().add(C50);
        C50.setBounds(20, 106, 45, 21);

        fckButtonGroup.add(C55);
        C55.setText("C55");
        getContentPane().add(C55);
        C55.setBounds(100, 46, 45, 21);

        fckButtonGroup.add(C60);
        C60.setText("C60");
        getContentPane().add(C60);
        C60.setBounds(100, 76, 45, 21);

        fckButtonGroup.add(C65);
        C65.setText("C65");
        getContentPane().add(C65);
        C65.setBounds(100, 106, 45, 21);

        fckButtonGroup.add(C70);
        C70.setText("C70");
        getContentPane().add(C70);
        C70.setBounds(180, 46, 45, 21);

        fckButtonGroup.add(C75);
        C75.setText("C75");
        getContentPane().add(C75);
        C75.setBounds(180, 76, 45, 21);

        fckButtonGroup.add(C80);
        C80.setText("C80");
        getContentPane().add(C80);
        C80.setBounds(180, 106, 45, 21);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(6, 192, 400, 3);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 254, 406, 3);

        jLabel4.setText("fck,j");
        jLabel4.setToolTipText("Resistência do concreto na data da protensão");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(6, 148, 50, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(66, 148, 100, 26);

        jLabel5.setText("fck");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 26, 40, 16);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 410, 88, 27);

        jLabel6.setText("CA-50 ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(6, 228, 36, 16);

        prestressedSteelButtonGroup.add(CP190_127);
        CP190_127.setText("CP 190 RB 12,7 - 7 fios");
        CP190_127.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CP190_127.setMaximumSize(new java.awt.Dimension(192, 24));
        CP190_127.setMinimumSize(new java.awt.Dimension(192, 24));
        CP190_127.setPreferredSize(new java.awt.Dimension(192, 24));
        getContentPane().add(CP190_127);
        CP190_127.setBounds(14, 307, 192, 24);

        prestressedSteelButtonGroup.add(CP190_152);
        CP190_152.setText("CP 190 RB 15,2 - 7 fios");
        CP190_152.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(CP190_152);
        CP190_152.setBounds(14, 337, 141, 21);

        prestressedSteelButtonGroup.add(CP190_157);
        CP190_157.setText("CP 190 RB 15,7 - 7 fios");
        CP190_157.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CP190_157.setMaximumSize(new java.awt.Dimension(192, 24));
        CP190_157.setMinimumSize(new java.awt.Dimension(192, 24));
        CP190_157.setPreferredSize(new java.awt.Dimension(192, 24));
        getContentPane().add(CP190_157);
        CP190_157.setBounds(14, 367, 192, 24);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double fck = 0.0;
        double tendonTension = 0.0;
        double tendonDiameter = 0.0;
        double passiveSteelBar = 50.0;

        if (C40.isSelected()) {
            fck = 40.0;
        } else if (C45.isSelected()) {
            fck = 45.0;
        } else if (C50.isSelected()) {
            fck = 50.0;
        } else if (C55.isSelected()) {
            fck = 55.0;
        } else if (C60.isSelected()) {
            fck = 60.0;
        } else if (C65.isSelected()) {
              fck = 65.0;
        } else if (C70.isSelected()) {
            fck = 70.0;
        } else if (C75.isSelected()) {
            fck = 75.0;
        } else if (C80.isSelected()) {
            fck = 80.0;
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o fck do concreto.");
        }

        if (CP190_127.isSelected()) {
            tendonDiameter = 1.27;
            tendonTension = 190;
        } else if (CP190_152.isSelected()) {
            tendonDiameter = 1.52;
            tendonTension = 190;

        } else if (CP190_157.isSelected()) {
            tendonDiameter = 1.57;
            tendonTension = 190;
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o fck do concreto.");

        }

        this.fck = fck;
        this.tendonDiameter = tendonDiameter;
        this.tendonTension = tendonTension;
        this.passiveSteelBar = passiveSteelBar;


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaterialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaterialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaterialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaterialJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MaterialJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton C40;
    private javax.swing.JRadioButton C45;
    private javax.swing.JRadioButton C50;
    private javax.swing.JRadioButton C55;
    private javax.swing.JRadioButton C60;
    private javax.swing.JRadioButton C65;
    private javax.swing.JRadioButton C70;
    private javax.swing.JRadioButton C75;
    private javax.swing.JRadioButton C80;
    private javax.swing.JRadioButton CP190_127;
    private javax.swing.JRadioButton CP190_152;
    private javax.swing.JRadioButton CP190_157;
    private javax.swing.ButtonGroup fckButtonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.ButtonGroup prestressedSteelButtonGroup;
    // End of variables declaration//GEN-END:variables
}
