/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ada.protende;

/**
 *
 * @author olgierd
 */
public class sectionPropertiesJFrame extends javax.swing.JFrame {

    /**
     * Creates new form sectionPropertiesJFrame
     */
    public sectionPropertiesJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sectionTypeButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sectionAreaText = new javax.swing.JTextField();
        inertiaText = new javax.swing.JTextField();
        inferiorFiberDistanceText = new javax.swing.JTextField();
        superiorFiberDistance = new javax.swing.JTextField();
        prestressedExcentricityText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        sectionTButton = new javax.swing.JRadioButton();
        sectionIButton = new javax.swing.JRadioButton();
        rectangularSectionButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(297, 550));
        getContentPane().setLayout(null);

        jLabel1.setText("<html>\n<p>A <sub>c</sub>  (cm<sup>2</sup>)</p>\n");
        jLabel1.setToolTipText("Área de seção transversal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 200, 80, 40);

        jLabel2.setText("<html>\n<p>I<sub>c</sub>  (cm<sup>4</sup>)</p>\n");
        jLabel2.setToolTipText("Momento de inércia");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 250, 80, 40);

        jLabel3.setText("<html>\n<p>y<sub>b</sub>  (cm)</p>\n");
        jLabel3.setToolTipText("Distância da fribra de base até o centroide da seção");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 300, 80, 40);

        jLabel4.setText("<html>\n<p>y<sub>t</sub>  (cm)</p>\n");
        jLabel4.setToolTipText("distância da fibra do topo até o cetroide da seção");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 350, 80, 40);

        jLabel5.setText("<html> <p>e<sub>p</sub>  (cm)</p> ");
        jLabel5.setToolTipText("distância do centroide da protensão até o centroide da seção");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 400, 80, 40);

        jLabel6.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Propriedades da seção");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 300, 24);
        getContentPane().add(sectionAreaText);
        sectionAreaText.setBounds(130, 200, 100, 30);
        getContentPane().add(inertiaText);
        inertiaText.setBounds(130, 250, 100, 30);
        getContentPane().add(inferiorFiberDistanceText);
        inferiorFiberDistanceText.setBounds(130, 300, 100, 30);
        getContentPane().add(superiorFiberDistance);
        superiorFiberDistance.setBounds(130, 350, 100, 30);
        getContentPane().add(prestressedExcentricityText);
        prestressedExcentricityText.setBounds(130, 400, 100, 30);

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo da seção"));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 30, 220, 140);

        sectionTypeButtonGroup.add(sectionTButton);
        sectionTButton.setText("seção T ou duplo T");
        getContentPane().add(sectionTButton);
        sectionTButton.setBounds(60, 70, 190, 21);

        sectionTypeButtonGroup.add(sectionIButton);
        sectionIButton.setText("seção I ou T invertido");
        getContentPane().add(sectionIButton);
        sectionIButton.setBounds(60, 100, 190, 21);

        sectionTypeButtonGroup.add(rectangularSectionButton);
        rectangularSectionButton.setText("seção Retangular");
        getContentPane().add(rectangularSectionButton);
        rectangularSectionButton.setBounds(60, 130, 170, 21);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sectionPropertiesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inertiaText;
    private javax.swing.JTextField inferiorFiberDistanceText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField prestressedExcentricityText;
    private javax.swing.JRadioButton rectangularSectionButton;
    private javax.swing.JTextField sectionAreaText;
    private javax.swing.JRadioButton sectionIButton;
    private javax.swing.JRadioButton sectionTButton;
    private javax.swing.ButtonGroup sectionTypeButtonGroup;
    private javax.swing.JTextField superiorFiberDistance;
    // End of variables declaration//GEN-END:variables
}
