/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ada.protende;

import javax.swing.JOptionPane;
import javax.swing.JTextField;
import util.Converter;

/**
 *
 * @author olgierd
 */
public class SectionPropertiesJFrame extends javax.swing.JFrame {

    private String sectionType;
    private double areaSection;
    private double inertia;
    private double inferiorFiberDist;
    private double superiorFiberDist;
    private double prestressExcentricity;

    /**
     * Creates new form sectionPropertiesJFrame
     */
    public SectionPropertiesJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sectionTypeButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sectionAreaText = new javax.swing.JTextField();
        inertiaText = new javax.swing.JTextField();
        inferiorFiberDistanceText = new javax.swing.JTextField();
        superiorFiberDistance = new javax.swing.JTextField();
        prestressedExcentricityText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        sectionTRadioBtn = new javax.swing.JRadioButton();
        section_I_RadioBtn = new javax.swing.JRadioButton();
        rectangularSectionRadioBtn = new javax.swing.JRadioButton();
        confirmPropertiesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(297, 550));
        getContentPane().setLayout(null);

        jLabel1.setText("<html>\n<p>A <sub>c</sub>  (cm<sup>2</sup>)</p>\n");
        jLabel1.setToolTipText("Área de seção transversal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 200, 80, 40);

        jLabel2.setText("<html>\n<p>I<sub>c</sub>  (cm<sup>4</sup>)</p>\n");
        jLabel2.setToolTipText("Momento de inércia");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 250, 80, 40);

        jLabel3.setText("<html>\n<p>y<sub>b</sub>  (cm)</p>\n");
        jLabel3.setToolTipText("Distância da fribra de base até o centroide da seção");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 300, 80, 40);

        jLabel4.setText("<html>\n<p>y<sub>t</sub>  (cm)</p>\n");
        jLabel4.setToolTipText("distância da fibra do topo até o cetroide da seção");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 350, 80, 40);

        jLabel5.setText("<html> <p>e<sub>p</sub>  (cm)</p> ");
        jLabel5.setToolTipText("distância do centroide da protensão até o centroide da seção");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 400, 80, 40);

        jLabel6.setFont(new java.awt.Font("Courier 10 Pitch", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Propriedades da seção");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 300, 23);
        getContentPane().add(sectionAreaText);
        sectionAreaText.setBounds(130, 200, 100, 30);
        getContentPane().add(inertiaText);
        inertiaText.setBounds(130, 250, 100, 30);
        getContentPane().add(inferiorFiberDistanceText);
        inferiorFiberDistanceText.setBounds(130, 300, 100, 30);
        getContentPane().add(superiorFiberDistance);
        superiorFiberDistance.setBounds(130, 350, 100, 30);
        getContentPane().add(prestressedExcentricityText);
        prestressedExcentricityText.setBounds(130, 400, 100, 30);

        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo da seção"));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(40, 30, 220, 140);

        sectionTypeButtonGroup.add(sectionTRadioBtn);
        sectionTRadioBtn.setText("seção T ou duplo T");
        getContentPane().add(sectionTRadioBtn);
        sectionTRadioBtn.setBounds(60, 70, 190, 24);

        sectionTypeButtonGroup.add(section_I_RadioBtn);
        section_I_RadioBtn.setText("seção I ou T invertido");
        getContentPane().add(section_I_RadioBtn);
        section_I_RadioBtn.setBounds(60, 100, 190, 24);

        sectionTypeButtonGroup.add(rectangularSectionRadioBtn);
        rectangularSectionRadioBtn.setText("seção Retangular");
        getContentPane().add(rectangularSectionRadioBtn);
        rectangularSectionRadioBtn.setBounds(60, 130, 170, 24);

        confirmPropertiesButton.setText("Confirmar");
        confirmPropertiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPropertiesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmPropertiesButton);
        confirmPropertiesButton.setBounds(129, 460, 100, 26);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPropertiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPropertiesButtonActionPerformed
        sectionType = "";
        if (sectionTRadioBtn.isSelected()) {
            System.out.println("Seção T ou duplo T.");
            sectionType = "sectionT";
        }
        if (section_I_RadioBtn.isSelected()) {
            System.out.println("Seção I.");
            sectionType = "sectionI";
        }
        if (rectangularSectionRadioBtn.isSelected()) {
            System.out.println("Seção retangular.");
            sectionType = "rectangular";

        }

        if (sectionType.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Tipo da seção não selecionado.");
            throw new IllegalArgumentException("section type not selected.");
        }

        trhowExceptionIfJTexTFieldIsEmpty(sectionAreaText);
        areaSection = Converter.textToDouble(sectionAreaText);

        trhowExceptionIfJTexTFieldIsEmpty(inertiaText);
        inertia = Converter.textToDouble(inertiaText);

        trhowExceptionIfJTexTFieldIsEmpty(inferiorFiberDistanceText);
        inferiorFiberDist = Converter.textToDouble(inferiorFiberDistanceText);

        trhowExceptionIfJTexTFieldIsEmpty(superiorFiberDistance);

        superiorFiberDist = Converter.textToDouble(superiorFiberDistance);
        
        trhowExceptionIfJTexTFieldIsEmpty(prestressedExcentricityText);
        prestressExcentricity = Converter.textToDouble(prestressedExcentricityText);

        System.out.println("Salvando dados de propriedades das seções...");
        //Fecha a JFrame sem perder os dados
        dispose();
    }//GEN-LAST:event_confirmPropertiesButtonActionPerformed

    private void trhowExceptionIfJTexTFieldIsEmpty(JTextField textField) {
        if (textField.getText().trim().isEmpty()) { // trim() remove espaços em branco
            JOptionPane.showMessageDialog(null, "Campos de texto de texto não pode estar vazio.");
            throw new IllegalArgumentException("TextField cannot be empty");
        }
    }

    public String getSectionType() {
        return sectionType;
    }

    public double getAreaSection() {
        return areaSection;
    }

    public double getInertia() {
        return inertia;
    }

    public double getInferiorFiberDist() {
        return inferiorFiberDist;
    }

    public double getSuperiorFiberDist() {
        return superiorFiberDist;
    }

    public double getPrestressExcentricity() {
        return prestressExcentricity;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SectionPropertiesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SectionPropertiesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmPropertiesButton;
    private javax.swing.JTextField inertiaText;
    private javax.swing.JTextField inferiorFiberDistanceText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField prestressedExcentricityText;
    private javax.swing.JRadioButton rectangularSectionRadioBtn;
    private javax.swing.JTextField sectionAreaText;
    private javax.swing.JRadioButton sectionTRadioBtn;
    private javax.swing.ButtonGroup sectionTypeButtonGroup;
    private javax.swing.JRadioButton section_I_RadioBtn;
    private javax.swing.JTextField superiorFiberDistance;
    // End of variables declaration//GEN-END:variables
}
